sonar.projectKey=yudi19key_servico-revenda-veiculos-clientes
sonar.organization=yudi19key
sonar.projectName=servico-revenda-veiculos-clientes
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes
sonar.sourceEncoding=UTF-8
