spring.application.name=veiculos-clientes

# DataSource - H2
spring.datasource.url=jdbc:h2:file:./data/veiculos_clientes;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.generate-unique-name=false

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# JPA / Hibernate
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# AWS
aws.region=us-east-1
aws.endpoint=
aws.sqs.clientes-commands-url=https://sqs.us-east-1.amazonaws.com/557187971532/revenda-clientes-commands
aws.kms.key-arn=arn:aws:kms:us-east-1:557187971532:key/6965c06c-da2b-4f4b-943c-0a7bc8ed90ac
